import Link from 'next/link';

const bodyClass =
  'text-pretty font-sans text-base leading-relaxed text-muted-foreground md:text-lg md:leading-[28px]';

const h2Class = 'font-sans text-lg font-semibold tracking-tight text-foreground md:text-xl';

export function PrivacyPolicyContent() {
  return (
    <article className="relative bg-background px-3 py-12 md:px-5 md:py-16">
      <header className="max-w-4xl border-b border-border pb-10">
        <p className="text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">Phrony</p>
        <h1 className="mt-3 font-sans text-3xl font-semibold tracking-tight text-foreground sm:text-4xl md:text-[2.5rem] md:leading-[1.15]">
          Privacy Policy
        </h1>
        <p className="mt-4 text-sm text-muted-foreground">
          Phrony Labs BV&nbsp;&nbsp;|&nbsp;&nbsp;KVK 42039600
        </p>
        <p className="mt-2 text-sm text-muted-foreground">Last updated: April 2025</p>
      </header>

      <div className="mx-auto mt-12 max-w-4xl space-y-10">
        <section className="space-y-4">
          <h2 className={h2Class}>1. Who We Are</h2>
          <div className={`space-y-4 ${bodyClass}`}>
            <p>
              Phrony Labs BV (&quot;Phrony&quot;, &quot;we&quot;, &quot;our&quot;) is the data controller for personal
              data collected through our website (phrony.com) and, where applicable, as data processor for personal data
              processed through our platform on behalf of our customers.
            </p>
            <p>Registered in the Netherlands under KVK number 42039600.</p>
            <p>
              Contact:{' '}
              <a
                href="mailto:privacy@phrony.com"
                className="text-foreground underline underline-offset-4 hover:text-primary"
              >
                privacy@phrony.com
              </a>
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className={h2Class}>2. What Data We Collect</h2>
          <div className="space-y-6">
            <div>
              <p className={`font-medium text-foreground ${bodyClass}`}>Website visitors:</p>
              <ul className={`list-decimal space-y-2 pl-6 ${bodyClass}`}>
                <li>
                  Contact information you provide (name, email, company) when requesting a demo, subscribing to updates,
                  or contacting us
                </li>
                <li>Technical data: IP address, browser type, device type, pages visited, referral source</li>
                <li>
                  Cookie data: analytics and functional cookies (see our{' '}
                  <Link href="/cookie-policy" className="text-foreground underline underline-offset-4 hover:text-primary">
                    Cookie Policy
                  </Link>
                  )
                </li>
              </ul>
            </div>
            <div>
              <p className={`font-medium text-foreground ${bodyClass}`}>Platform users (SaaS):</p>
              <ul className={`list-decimal space-y-2 pl-6 ${bodyClass}`}>
                <li>Account information: name, email, organisation, role</li>
                <li>Usage data: sessions run, features used, API calls made</li>
                <li>
                  Platform logs: session, run, and step logs generated by AI agents (these may contain personal data
                  depending on the Customer&apos;s use case)
                </li>
                <li>Billing information: processed through our payment provider</li>
              </ul>
            </div>
            <div>
              <p className={`font-medium text-foreground ${bodyClass}`}>Platform users (self-hosted):</p>
              <ul className={`list-decimal space-y-2 pl-6 ${bodyClass}`}>
                <li>Account information for licence management only (name, email, organisation)</li>
                <li>
                  We do not collect, access, or process any data from self-hosted deployments. All platform data
                  remains on the Customer&apos;s infrastructure.
                </li>
              </ul>
            </div>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className={h2Class}>3. How We Use Your Data</h2>
          <p className={bodyClass}>We process personal data for the following purposes:</p>
          <ol className={`list-decimal space-y-3 pl-6 ${bodyClass}`}>
            <li>
              Providing and operating the Platform (legal basis: performance of contract, GDPR Article 6(1)(b))
            </li>
            <li>Account management and customer support (legal basis: performance of contract)</li>
            <li>
              Billing and invoicing (legal basis: performance of contract and legal obligation, GDPR Article 6(1)(c))
            </li>
            <li>Product improvement and analytics (legal basis: legitimate interest, GDPR Article 6(1)(f))</li>
            <li>Marketing communications, only with consent (legal basis: consent, GDPR Article 6(1)(a))</li>
            <li>
              Compliance with legal obligations, including tax and financial reporting (legal basis: legal obligation)
            </li>
          </ol>
          <p className={bodyClass}>
            We do not sell personal data. We do not use Customer data to train AI models.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className={h2Class}>4. Data Processing on Behalf of Customers</h2>
          <div className={`space-y-4 ${bodyClass}`}>
            <p>
              <span className="font-medium text-foreground">SaaS deployments:</span> When Customers deploy AI agents on
              our managed platform, Phrony acts as a data processor under GDPR Article 28. We process Customer data
              solely on the Customer&apos;s instructions and for the purpose of providing the Platform service. A Data
              Processing Agreement (DPA) governs this relationship.
            </p>
            <p>
              <span className="font-medium text-foreground">Self-hosted deployments:</span> Phrony does not act as a
              data processor. The Customer is both data controller and processor for all data processed on their own
              infrastructure. Phrony has no access to Customer data in self-hosted deployments.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className={h2Class}>5. Sub-Processors</h2>
          <p className={bodyClass}>For SaaS deployments, we use the following categories of sub-processors:</p>
          <ol className={`list-decimal space-y-3 pl-6 ${bodyClass}`}>
            <li>Cloud infrastructure providers (hosting and compute)</li>
            <li>LLM providers (as configured by the Customer — e.g., OpenAI, Anthropic, Mistral)</li>
            <li>Payment processors</li>
            <li>Analytics tools (anonymised data only)</li>
          </ol>
          <p className={bodyClass}>
            A current list of sub-processors is available at{' '}
            <Link href="/sub-processors" className="text-foreground underline underline-offset-4 hover:text-primary">
              phrony.com/sub-processors
            </Link>{' '}
            and is updated when changes occur. Customers are notified of new sub-processors with a minimum 14-day notice
            period and may object if the new sub-processor creates a compliance concern for their use case.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className={h2Class}>6. International Data Transfers</h2>
          <div className={`space-y-4 ${bodyClass}`}>
            <p>
              Phrony is based in the Netherlands (EU). We aim to keep all personal data within the European Economic Area
              (EEA).
            </p>
            <p>
              Where data is transferred outside the EEA (e.g., to LLM providers based in the United States), we rely on:
            </p>
            <ol className="list-decimal space-y-2 pl-6">
              <li>EU-US Data Privacy Framework (where the recipient is certified), or</li>
              <li>Standard Contractual Clauses (SCCs) approved by the European Commission</li>
            </ol>
            <p>
              For SaaS Enterprise customers, Phrony offers an EU-only processing tier where all data processing,
              including LLM API calls, is routed through EU-based infrastructure and providers.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className={h2Class}>7. Data Retention</h2>
          <p className={bodyClass}>We retain personal data only as long as necessary for the purposes described in this policy:</p>
          <ol className={`list-decimal space-y-3 pl-6 ${bodyClass}`}>
            <li>Account data: for the duration of the Customer relationship, plus 12 months after account closure</li>
            <li>
              Platform logs (SaaS): retained to operate and secure the service; we do not vary retention by plan
              tier. Deletion requests and legal obligations may still require retention limits in specific cases.
            </li>
            <li>Billing records: 7 years (Dutch tax law requirement)</li>
            <li>Marketing data: until consent is withdrawn</li>
          </ol>
          <p className={bodyClass}>
            Self-hosted customers control their own data retention. Phrony does not retain any data from self-hosted
            deployments.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className={h2Class}>8. Your Rights</h2>
          <p className={bodyClass}>Under the GDPR, you have the following rights regarding your personal data:</p>
          <ol className={`list-decimal space-y-3 pl-6 ${bodyClass}`}>
            <li>Right of access (Article 15) — request a copy of your data</li>
            <li>Right to rectification (Article 16) — correct inaccurate data</li>
            <li>Right to erasure (Article 17) — request deletion of your data</li>
            <li>Right to restrict processing (Article 18)</li>
            <li>Right to data portability (Article 20) — receive your data in a structured format</li>
            <li>Right to object (Article 21) — object to processing based on legitimate interest</li>
            <li>Right to withdraw consent at any time for consent-based processing</li>
          </ol>
          <p className={bodyClass}>
            To exercise any of these rights, contact us at{' '}
            <a
              href="mailto:privacy@phrony.com"
              className="text-foreground underline underline-offset-4 hover:text-primary"
            >
              privacy@phrony.com
            </a>
            . We will respond within 30 days.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className={h2Class}>9. Security</h2>
          <p className={bodyClass}>
            We implement appropriate technical and organisational measures to protect personal data, including:
          </p>
          <ol className={`list-decimal space-y-2 pl-6 ${bodyClass}`}>
            <li>Encryption in transit (TLS) and at rest</li>
            <li>Role-based access control for all platform access</li>
            <li>Encrypted secrets vault for credentials and API keys</li>
            <li>Multi-tenancy isolation at the database level</li>
            <li>Immutable, tamper-resistant audit logging</li>
            <li>Regular security assessments and vulnerability scanning</li>
          </ol>
        </section>

        <section className="space-y-4">
          <h2 className={h2Class}>10. Cookies</h2>
          <div className={`space-y-4 ${bodyClass}`}>
            <p>
              Our website uses cookies for essential functionality and analytics. We use:
            </p>
            <ol className="list-decimal space-y-2 pl-6">
              <li>Essential cookies: required for the website to function (no consent required)</li>
              <li>Analytics cookies: to understand how visitors use our website (consent required)</li>
            </ol>
            <p>
              You can manage your cookie preferences at any time through the cookie banner on our website or through your
              browser settings.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className={h2Class}>11. Data Protection Officer</h2>
          <div className={`space-y-4 ${bodyClass}`}>
            <p>For questions or concerns about our data processing practices, contact:</p>
            <p>
              Privacy contact:{' '}
              <a
                href="mailto:privacy@phrony.com"
                className="text-foreground underline underline-offset-4 hover:text-primary"
              >
                privacy@phrony.com
              </a>
            </p>
            <p>Phrony Labs BV, the Netherlands</p>
            <p>
              You also have the right to lodge a complaint with the Dutch Data Protection Authority (Autoriteit
              Persoonsgegevens) at{' '}
              <a
                href="https://autoriteitpersoonsgegevens.nl"
                className="text-foreground underline underline-offset-4 hover:text-primary"
                target="_blank"
                rel="noopener noreferrer"
              >
                autoriteitpersoonsgegevens.nl
              </a>
              .
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className={h2Class}>12. Changes to This Policy</h2>
          <p className={bodyClass}>
            We may update this Privacy Policy from time to time. Material changes will be communicated via email or
            through our website. The &quot;Last updated&quot; date at the top of this policy indicates the most recent
            revision.
          </p>
        </section>
      </div>
    </article>
  );
}
